# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-07-10 14:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20170710_1411'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailverifyrecord',
            name='send_type',
            field=models.CharField(choices=[('register', '\u6ce8\u518c'), ('forget', '\u627e\u56de\u5bc6\u7801'), ('update', '\u4fee\u6539\u90ae\u7bb1')], max_length=10),
        ),
    ]
