# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-07-09 04:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='age',
            field=models.IntegerField(default=20, verbose_name='\u6559\u5e08\u5e74\u9f84'),
        ),
    ]
